version: "3.7"

services:
    app:
        build: ./
        image: babbleapp
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 5000:5000
        environment:
            FLASK_ENV: development
            FLASK_APP: /app/app.py
        labels:
            traefik.http.routers.flask.rule: PathPrefix(`/`)

    proxy:
        image: traefik:v2.1
        command: --api.insecure=true --providers.docker
        ports:
        - 80:80
        - 8080:8080
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock 