version: "3.7"

services:
    app:
        build: ./
        image: babbleapp
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 5000:5000
        environment:
            FLASK_ENV: development
            FLASK_APP: /app/app.py
            DEBUG_METRICS: "false"
        labels:
            traefik.http.routers.flask.rule: PathPrefix(/)

    proxy:
        image: traefik:v2.1
        command: --api.insecure=true --providers.docker
        ports:
        - 80:80
        - 8080:8080
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock 

    mongo:
        image: mongo

    prometheus:
        image: prom/prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana
        volumes:
            - grafana-volume:/var/lib/grafana
        ports:
            - 3000:3000

volumes:
    grafana-volume: